### ISSUE TITLE
H5Fget_name Require a File Object (API indicates differently)

### ISSUE THREAD

**Issue by ron-kuhn** [HDFGroup/vol-rest#14]
@jhendersonHDF or anyone else,
From the documentation for H5Fget_name:
hid_t obj_id - IN: Identifier of the object for which the associated file name is sought; may be a file, group, dataset, attribute, or named datatype

H5VLnative_file.c supports this but vol-rest does NOT.

Is there a workaround to get the file_id from any obj_id until this is supported?

**Comment by ron-kuhn** [comment]
@jreadey, do you have a workaround for the above problem?

**Comment by jhendersonHDF** [comment]
Hi @ron-kuhn, is it possible to check if https://github.com/HDFGroup/vol-rest/pull/17 fixes this for you? The alternative would have been to call H5Iget_file_id, but the connector doesn't support that call currently.

**Comment by ron-kuhn** [comment]
2 projects (h5vl_test and h5_test_testhdf5) are both giving unresolved externals for snprintf. Any

**Comment by ron-kuhn** [comment]
I support file based and s3 based hdf5 files. How can I check whether I am using native or a VOL?

**Comment by mattjala** [comment]
> I support file based and s3 based hdf5 files. How can I check whether I am using native or a VOL?

Native will be used unless the environment variable `HDF5_PLUGIN_PATH` is set to a VOL installation, and the environment variable `HDF5_VOL_CONNECTOR` is set to the corresponding VOL name (in this case, `REST`).

**Comment by mattjala** [comment]
If you've linked the library and included `rest_vol_public.h`, then it should be using the VOL. One way to check would be to try to read from a file on your server. You could also try calling a function which isn't yet supported in the REST VOL, such as `H5Fget_fileno`, and checking that it returns an error message saying it is unsupported.

**Comment by ron-kuhn** [comment]
@mattjala, I had to comment out the definitions for HDsnprintf and HDvsnprintf in \vol-rest\test\vol-tests\h5win32defs.h to get the VOL to build.

**Comment by ron-kuhn** [comment]
@mattjala, your changes look good for what I requested. 

I see that H5Dextend is not supported for rest vol. I want to store many images but don't necessarily know how many will be maximum. I will workaround for now, but do you know if it is planned in the near future?

**Comment by mattjala** [comment]
> @mattjala, your changes look good for what I requested.
> 
> I see that H5Dextend is not supported for rest vol. I want to store many images but don't necessarily know how many will be maximum. I will workaround for now, but do you know if it is planned in the near future?

Yes, it is planned for implementation soon.
