### ISSUE TITLE
H5Sselect_hyperslab required when using filespace from H5Dget_space

### ISSUE THREAD

**Issue by jpswinski** [HDFGroup/vol-rest#2]
When calling H5Dread, if the filespace parameter was allocated by a call to H5Dget_space, you must also call H5Sselect_hyperslab on the filespace in order for the read to work.  If you don't then the vol-rest connector returns: 

```
#000: /home/ubuntu/dependencies/vol-rest/src/rest_vol_dataset.c line 592 in RV_dataset_read(): 400 - Malformed/Bad request for resource
```

This is inconsistent with the regular hdf5 library which works fine when you pass the filespace gotten from the H5Dget_space directly into the H5Dread function.

**Comment by jhendersonHDF** [comment]
Thanks for reporting this; it seems like HDF5 probably sets an "All" selection by default on a dataspace when it is created, which the REST VOL connector currently is not doing when creating/opening a dataset or attribute. Let me investigate and add another test for this.

**Comment by mattjala** [comment]
I was unable to replicate this - it seemed to have been fixed. This can be reopened if it comes up again.
