### ISSUE TITLE
Closing File Causes Errors With Child Groups

### ISSUE THREAD

**Issue by ron-kuhn** [HDFGroup/vol-rest#20]
I am using H5::H5File to create a file, then create a group (called Images) under the root group that everything is created from. After this, I don't need access to the H5File object so it is deleted but the Images group is saved. If I create anything off the Images group after deleting the H5File object (closing the file), I receive errors from the vol-rest. This doesn't have any problem with the native (file-based) vol (the file doesn't close till all the opened objects from the file are closed). Workaround is to save the H5File object also. This workaround work for now until users delete my object before done with the children.

**Comment by ron-kuhn** [comment]
This is because all the RV_object_t objects contain a **copy** of the domain's (file's) RV_object_t. This is freed when the file is closed.

**Comment by mattjala** [comment]
Fixed by #30, which changes groups, datasets, and datatypes to copy the file's domain.
