### ISSUE TITLE
Dataset Read Does Not Support Subset of Compound Data Members

### ISSUE THREAD

**Issue by ron-kuhn** [HDFGroup/vol-rest#21]
I have a dataset consisting of a compound datatype:

- Name - 64 characters
- AcquisitionTimeUTC - I64LE
- CenterZ - F64LE
- PixelSizeZ - F64LE

I write all the rows of the dataset at one time. When I browse through the HSDS objects and download the dataset, I see that the data was written correctly. If I only want to return the Names for all the rows, it says it is successful but the 2nd Name starts with data from the 1st AcquisitionTimeUTC row.

**Comment by mattjala** [comment]
Resolved in #107
