### ISSUE TITLE
verify large selections work for reads and writes

### ISSUE THREAD

**Issue by jreadey** [HDFGroup/vol-rest#23]
Previously HSDS had a limitation of 100mb for any GET or POST request.  This shouldn't be a factor since streaming support was added to HSDS.
Check this out by creating a test to write then read back a large selection.

**Comment by mattjala** [comment]
I tested it - the REST VOL works fine uploading and downloading gigabytes of data after #26

**Comment by ron-kuhn** [comment]
@mattjala, latest build fails with compiler error rest_vol.c line 1270. Changed to:
`memcpy(buffer, (const char*)uinfo->buffer + uinfo->bytes_sent, data_size);`
