### ISSUE TITLE
CTest: h5vL_test - Attribute test failed

### ISSUE THREAD

**Issue by jwsblokland** [HDFGroup/vol-rest#46]
When I build REST VOL API using CMake and run ctest, the test h5vl_test fails. Looking at the verbose output of this test, the following attribute test has failed:
```
Testing H5Aopen with an invalid AAPL                                *FAILED*
```

Currently, I am not sure why this attribute tests fails.

**Comment by mattjala** [comment]
This test passes when I run it locally - could you share information about your OS, HDF5 version and HDF5 build options, and how you built the VOL? Does the test output have an `HDF5 REST VOL-DIAG` /`HDF5-DIAG` error stack?
