### ISSUE TITLE
Fill values are unsupported

### ISSUE THREAD

**Issue by jpswinski** [HDFGroup/vol-rest#5]
HDF5 REST VOL-DIAG: Error detected in HDF5 REST VOL (1.0.0) thread 0:
#000: /vol-rest/src/rest_vol_dataset.c line 1368 in RV_parse_dataset_creation_properties_callback(): warning: dataset fill values are unsupported
major: Dataset
minor: Feature is unsupported

**Comment by jreadey** [comment]
There's a bit of a problem in that some fill values can't be directing encoded in JSON.
One idea would be to base-64 encode the fillvalue in POST dataset.
