### ISSUE TITLE
'https://bitbucket.hdfgroup.org' account required to build VOL-REST plugin

### ISSUE THREAD

**Issue by gesalous** [HDFGroup/vol-rest#52]
Hello, 
when I try to build vol-rest plugin I get the following output
cmake ../ -DPREBUILT_HDF5_DIR=/usr/local/lib -DHDF5_VOL_REST_ENABLE_CURL_DEBUG=ON -DHDF5_VOL_REST_ENABLE_DEBUG=ON
-- The C compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "2.41.0") 
-- Found CURL: /usr/lib/libcurl.so (found version "8.2.1")  
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.1") 
CMake Warning (dev) at /home/gesalous/.local/lib/python3.11/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (yajl) does
  not match the name of the calling package (YAJL).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMake/FindYAJL.cmake:22 (find_package_handle_standard_args)
  CMakeLists.txt:127 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found yajl: /usr/lib/libyajl.so  
-- VERSION: 0.1.0
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- VOL test submodule not found, checking it out
Cloning into '/home/gesalous/HDF5_staff/vol-rest/src/hdf5'...
Username for 'https://bitbucket.hdfgroup.org': get

However, I do not have one, and as I can see, I cannot register for a new account for https://bitbucket.hdfgroup.org. What am I missing?
Thanks

**Comment by jhendersonHDF** [comment]
Hi @gesalous, are you possibly using an old existing clone of the repository? The current master branch should have the VOL tests submodule pointing to our VOL tests repository on GitHub and should clone using HTTPS so you won't need an account. It may be worth making a new clone of this repository and trying that.

**Comment by mattjala** [comment]
This is likely due to using an old clone of the repository that sourced the `vol-tests` repo from bitbucket. Since there was no followup from user, I'll close this for now.
