### ISSUE TITLE
H5Fis_accessible: reports error message

### ISSUE THREAD

**Issue by jwsblokland** [HDFGroup/vol-rest#59]
When I use the function `H5Fis_accessible()` to verify if my code can access certain file, I always the following error message like this

```
HDF5 REST VOL-DIAG: Error detected in HDF5 REST VOL (1.0.0) thread 1:
  #000: /glb/data/SeismicApps3/nljbl6/vol-rest/src/src/rest_vol_file.c line 400 in RV_file_open(): 410 - Resource has been deleted
    major: File accessibility
    minor: Unable to open file
```

This is a bit confusing. Originally, I thought I did something wrong but my code does exactly what it suppose to do for this case. Would it be possible to suppress this error message for `H5Dis_accessible()`? For now, I just ignore it, but I know for sure it will be confusing for other people when they start using my code in combination with HSDS.

**Comment by mattjala** [comment]
Fixed in #60
